package com.finwin.payyanur.ckyc.supportClass;

import com.finwin.payyanur.ckyc.DropDownListClass.CountryGetSet;
import com.finwin.payyanur.ckyc.DropDownListClass.StateGetSet;

import java.util.ArrayList;

public class CountryAndStateList {

    public static ArrayList<StateGetSet> stateList = new ArrayList<>();

    static {
        stateList.add(new StateGetSet("AN", "Andaman & Nicobar"));
        stateList.add(new StateGetSet("AP", "Andhra Pradesh"));
        stateList.add(new StateGetSet("AR", "Arunachal Pradesh"));
        stateList.add(new StateGetSet("AS", "Assam"));
        stateList.add(new StateGetSet("BR", "Bihar"));
        stateList.add(new StateGetSet("CH", "Chandigarh"));
        stateList.add(new StateGetSet("CG", "Chattisgarh"));
        stateList.add(new StateGetSet("DN", "Dadra and Nagar Haveli"));
        stateList.add(new StateGetSet("DD", "Daman & Diu"));
        stateList.add(new StateGetSet("DL", "Delhi"));
        stateList.add(new StateGetSet("GA", "Goa"));
        stateList.add(new StateGetSet("GJ", "Gujarat"));
        stateList.add(new StateGetSet("HR", "Haryana"));
        stateList.add(new StateGetSet("HP", "Himachal Pradesh"));
        stateList.add(new StateGetSet("JK", "Jammu & Kashmir"));
        stateList.add(new StateGetSet("JH", "Jharkhand"));
        stateList.add(new StateGetSet("KA", "Karnataka"));
        stateList.add(new StateGetSet("KL", "Kerala"));
        stateList.add(new StateGetSet("LD", "Lakshadweep"));
        stateList.add(new StateGetSet("MP", "Madhya Pradesh"));
        stateList.add(new StateGetSet("MH", "Maharashtra"));
        stateList.add(new StateGetSet("MN", "Manipur"));
        stateList.add(new StateGetSet("ML", "Meghalaya"));
        stateList.add(new StateGetSet("MZ", "Mizoram"));
        stateList.add(new StateGetSet("NL", "Nagaland"));
        stateList.add(new StateGetSet("OR", "Orissa"));
        stateList.add(new StateGetSet("PY", "Pondicherry"));
        stateList.add(new StateGetSet("PB", "Punjab"));
        stateList.add(new StateGetSet("RJ", "Rajasthan"));
        stateList.add(new StateGetSet("SK", "Sikkim"));
        stateList.add(new StateGetSet("TN", "Tamil Nadu"));
        stateList.add(new StateGetSet("TS", "Telangana"));
        stateList.add(new StateGetSet("TR", "Tripura"));
        stateList.add(new StateGetSet("UP", "Uttar Pradesh"));
        stateList.add(new StateGetSet("UA", "Uttarakhand"));
        stateList.add(new StateGetSet("WB", "West Bengal"));
        stateList.add(new StateGetSet("XX", "Other"));
    }

    //====================

    public static ArrayList<CountryGetSet> countryList = new ArrayList<>();

    //Add countries
    static {
        countryList.add(new CountryGetSet("AF", "Afghanistan "));
        countryList.add(new CountryGetSet("DO", "Dominican Republic "));
        countryList.add(new CountryGetSet("LY", "Libya"));
        countryList.add(new CountryGetSet("PM", "Saint Pierre and Miquelon "));
        countryList.add(new CountryGetSet("AX", "Aland Islands"));
        countryList.add(new CountryGetSet("EC", "Ecuador "));
        countryList.add(new CountryGetSet("LI", "Liechtenstein "));
        countryList.add(new CountryGetSet("VC", "Saint Vincent and the Grenadines "));
        countryList.add(new CountryGetSet("AL", "Albania"));
        countryList.add(new CountryGetSet("EG", "Egypt "));
        countryList.add(new CountryGetSet("LT", "Lithuania "));
        countryList.add(new CountryGetSet("WS", "Samoa "));
        countryList.add(new CountryGetSet("DZ", "Algeria "));
        countryList.add(new CountryGetSet("SV", "Salvador "));
        countryList.add(new CountryGetSet("LU", "Luxembourg "));
        countryList.add(new CountryGetSet("SM", "San Marino "));
        countryList.add(new CountryGetSet("AS", "American Samoa "));
        countryList.add(new CountryGetSet("GQ", "Equatorial Guinea "));
        countryList.add(new CountryGetSet("MO", "Macao "));
        countryList.add(new CountryGetSet("ST", "Sao Tome and Principe "));
        countryList.add(new CountryGetSet("AD", "Andorra "));
        countryList.add(new CountryGetSet("ER", "Eritrea "));
        countryList.add(new CountryGetSet("MK", "Macedonia, the former Yugoslav Republic of"));
        countryList.add(new CountryGetSet("SA", "Saudi Arabia"));
        countryList.add(new CountryGetSet("AO", "Angola "));
        countryList.add(new CountryGetSet("EE", "Estonia "));
        countryList.add(new CountryGetSet("MG", "Madagascar "));
        countryList.add(new CountryGetSet("SN", "Senegal "));
        countryList.add(new CountryGetSet("AI", "Anguilla "));
        countryList.add(new CountryGetSet("ET", "Ethiopia "));
        countryList.add(new CountryGetSet("MW", "Malawi "));
        countryList.add(new CountryGetSet("RS", "Serbia "));
        countryList.add(new CountryGetSet("AQ", "Antarctica "));
        countryList.add(new CountryGetSet("FK", "Falkland Islands (Malvinas) "));
        countryList.add(new CountryGetSet("MY", "Malaysia "));
        countryList.add(new CountryGetSet("SC", "Seychelles "));
        countryList.add(new CountryGetSet("AG", "Antigua and Barbuda "));
        countryList.add(new CountryGetSet("FO", "Faroe Islands "));
        countryList.add(new CountryGetSet("MV", "Maldives "));
        countryList.add(new CountryGetSet("SL", "Sierra Leone "));
        countryList.add(new CountryGetSet("AR", "Argentina "));
        countryList.add(new CountryGetSet("FJ", "Fiji "));
        countryList.add(new CountryGetSet("ML", "Mali"));
        countryList.add(new CountryGetSet("SG", "Singapore "));
        countryList.add(new CountryGetSet("AM", "Armenia "));
        countryList.add(new CountryGetSet("FI", "Finland "));
        countryList.add(new CountryGetSet("MT", "Malta "));
        countryList.add(new CountryGetSet("SX", "Sint Maarten (Dutch part) "));
        countryList.add(new CountryGetSet("AW", "Aruba "));
        countryList.add(new CountryGetSet("FR", "France "));
        countryList.add(new CountryGetSet("MH", "Marshall Islands "));
        countryList.add(new CountryGetSet("SK", "Slovakia "));
        countryList.add(new CountryGetSet("AU", "Australia "));
        countryList.add(new CountryGetSet("GF", "French Guiana "));
        countryList.add(new CountryGetSet("MQ", "Martinique "));
        countryList.add(new CountryGetSet("SI", "Slovenia "));
        countryList.add(new CountryGetSet("AT", "Austria "));
        countryList.add(new CountryGetSet("PF", "French Polynesia "));
        countryList.add(new CountryGetSet("MR", "Mauritania "));
        countryList.add(new CountryGetSet("SB", "Solomon Islands "));
        countryList.add(new CountryGetSet("AZ", "Azerbaijan "));
        countryList.add(new CountryGetSet("TF", "French Southern Territories "));
        countryList.add(new CountryGetSet("MU", "Mauritius "));
        countryList.add(new CountryGetSet("SO", "Somalia "));
        countryList.add(new CountryGetSet("BS", "Bahamas "));
        countryList.add(new CountryGetSet("GA", "Gabon"));
        countryList.add(new CountryGetSet("YT", "Mayotte "));
        countryList.add(new CountryGetSet("ZA", "South Africa "));
        countryList.add(new CountryGetSet("BH", "Bahrain "));
        countryList.add(new CountryGetSet("GM", "Gambia "));
        countryList.add(new CountryGetSet("MX", "Mexico "));
        countryList.add(new CountryGetSet("GS", "South Georgia and the South Sandwich Islands"));
        countryList.add(new CountryGetSet("BD", "Bangladesh "));
        countryList.add(new CountryGetSet("GE", "Georgia "));
        countryList.add(new CountryGetSet("FM", "Micronesia, Federated States of "));
        countryList.add(new CountryGetSet("SS", "South Sudan "));
        countryList.add(new CountryGetSet("BB", "Barbados "));
        countryList.add(new CountryGetSet("DE", "Germany "));
        countryList.add(new CountryGetSet("MD", "Moldova, Republic of "));
        countryList.add(new CountryGetSet("ES", "Spain"));
        countryList.add(new CountryGetSet("BY", "Belarus "));
        countryList.add(new CountryGetSet("GH", "Ghana "));
        countryList.add(new CountryGetSet("MC", "Monaco "));
        countryList.add(new CountryGetSet("LK", "Sri Lanka "));
        countryList.add(new CountryGetSet("BE", "Belgium "));
        countryList.add(new CountryGetSet("GI ", "Gibraltar "));
        countryList.add(new CountryGetSet("MN", "Mongolia "));
        countryList.add(new CountryGetSet("SD", "Sudan "));
        countryList.add(new CountryGetSet("BZ", "Belize "));
        countryList.add(new CountryGetSet("GR", "Greece "));
        countryList.add(new CountryGetSet("ME", "Montenegro "));
        countryList.add(new CountryGetSet("SR", "Suriname "));
        countryList.add(new CountryGetSet("BJ", "Benin "));
        countryList.add(new CountryGetSet("GL", "Greenland "));
        countryList.add(new CountryGetSet("MS", "Montserrat "));
        countryList.add(new CountryGetSet("SJ", "Svalbard and Jan Mayen "));
        countryList.add(new CountryGetSet("BM", "Bermuda "));
        countryList.add(new CountryGetSet("GD", "Grenada "));
        countryList.add(new CountryGetSet("MA", "Morocco "));
        countryList.add(new CountryGetSet("SZ", "Swaziland "));
        countryList.add(new CountryGetSet("BT", "Bhutan "));
        countryList.add(new CountryGetSet("GP", "Guadeloupe "));
        countryList.add(new CountryGetSet("MZ", "Mozambique "));
        countryList.add(new CountryGetSet("SE", "Sweden "));
        countryList.add(new CountryGetSet("BO", "Bolivia, Plurinational State of "));
        countryList.add(new CountryGetSet("GU", "Guam"));
        countryList.add(new CountryGetSet("MM", "Myanmar "));
        countryList.add(new CountryGetSet("CH", "Switzerland "));
        countryList.add(new CountryGetSet("BQ", "Bonaire, Sint Eustatius and Saba "));
        countryList.add(new CountryGetSet("GT", "Guatemala "));
        countryList.add(new CountryGetSet("NA", "Namibia "));
        countryList.add(new CountryGetSet("SY", "Syrian Arab Republic "));
        countryList.add(new CountryGetSet("BA", "Bosnia and Herzegovina "));
        countryList.add(new CountryGetSet("GG", "Guernsey "));
        countryList.add(new CountryGetSet("NR", "Nauru "));
        countryList.add(new CountryGetSet("TW", "Taiwan, Province of China "));
        countryList.add(new CountryGetSet("BW", "Botswana "));
        countryList.add(new CountryGetSet("GN", "Guinea "));
        countryList.add(new CountryGetSet("NP", "Nepal"));
        countryList.add(new CountryGetSet("TJ", "Tajikistan "));
        countryList.add(new CountryGetSet("BV", "Bouvet Island "));
        countryList.add(new CountryGetSet("GW", "Guinea-Bissau "));
        countryList.add(new CountryGetSet("NL", "Netherlands "));
        countryList.add(new CountryGetSet("TZ", "Tanzania, United Republic of "));
        countryList.add(new CountryGetSet("BR", "Brazil"));
        countryList.add(new CountryGetSet("GY", "Guyana "));
        countryList.add(new CountryGetSet("NC", "New Caledonia "));
        countryList.add(new CountryGetSet("TH", "Thailand "));
        countryList.add(new CountryGetSet("IO", "British Indian Ocean Territory "));
        countryList.add(new CountryGetSet("HT", "Haiti "));
        countryList.add(new CountryGetSet("NZ", "New Zealand "));
        countryList.add(new CountryGetSet("TL", "Timor-Leste "));
        countryList.add(new CountryGetSet("BN", "Brunei Darussalam "));
        countryList.add(new CountryGetSet("HM", "Heard Island and McDonald Islands "));
        countryList.add(new CountryGetSet("NI", "Nicaragua "));
        countryList.add(new CountryGetSet("TG", "Togo "));
        countryList.add(new CountryGetSet("BG", "Bulgaria "));
        countryList.add(new CountryGetSet("VA", "Holy See (Vatican City State) "));
        countryList.add(new CountryGetSet("NE", "Niger "));
        countryList.add(new CountryGetSet("TK", "Tokelau "));
        countryList.add(new CountryGetSet("BF", "Burkina Faso "));
        countryList.add(new CountryGetSet("HN ", "Honduras "));
        countryList.add(new CountryGetSet("NG", "Nigeria "));
        countryList.add(new CountryGetSet("TO", "Tonga "));
        countryList.add(new CountryGetSet("BI", "Burundi "));
        countryList.add(new CountryGetSet("HK", "Hong Kong "));
        countryList.add(new CountryGetSet("NU", "Niue "));
        countryList.add(new CountryGetSet("TT", "Trinidad and Tobago"));
        countryList.add(new CountryGetSet("CV", "Cabo Verde "));
        countryList.add(new CountryGetSet("HU", "Hungary "));
        countryList.add(new CountryGetSet("NF", "Norfolk Island"));
        countryList.add(new CountryGetSet("TN", "Tunisia "));
        countryList.add(new CountryGetSet("KH", "Cambodia "));
        countryList.add(new CountryGetSet("IS", "Iceland "));
        countryList.add(new CountryGetSet("MP", "Northern Mariana Islands "));
        countryList.add(new CountryGetSet("TR", "Turkey "));
        countryList.add(new CountryGetSet("CM", "Cameroon "));
        countryList.add(new CountryGetSet("IN", "India "));
        countryList.add(new CountryGetSet("NO", "Norway "));
        countryList.add(new CountryGetSet("TM", "Turkmenistan "));
        countryList.add(new CountryGetSet("CA", "Canada "));
        countryList.add(new CountryGetSet("ID", "Indonesia"));
        countryList.add(new CountryGetSet("OM", "Oman"));
        countryList.add(new CountryGetSet("TC", "Turks and Caicos Islands"));
        countryList.add(new CountryGetSet("KY", "Cayman Islands "));
        countryList.add(new CountryGetSet("IR", "Iran, Islamic Republic of "));
        countryList.add(new CountryGetSet("PK", "Pakistan "));
        countryList.add(new CountryGetSet("TV", "Tuvalu "));
        countryList.add(new CountryGetSet("CF", "Central African Republic "));
        countryList.add(new CountryGetSet("IQ", "Iraq "));
        countryList.add(new CountryGetSet("PW", "Palau "));
        countryList.add(new CountryGetSet("UG", "Uganda "));
        countryList.add(new CountryGetSet("TD", "Chad "));
        countryList.add(new CountryGetSet("IE", "Ireland "));
        countryList.add(new CountryGetSet("PS", "Palestine, State of "));
        countryList.add(new CountryGetSet("UA", "Ukraine "));
        countryList.add(new CountryGetSet("CL", "Chile "));
        countryList.add(new CountryGetSet("IM", "Isle of Man "));
        countryList.add(new CountryGetSet("PA", "Panama "));
        countryList.add(new CountryGetSet("AE", "United Arab Emirates "));
        countryList.add(new CountryGetSet("CN", "China "));
        countryList.add(new CountryGetSet("IL", "Israel "));
        countryList.add(new CountryGetSet("PG", "Papua New Guinea "));
        countryList.add(new CountryGetSet("GB", "United Kingdom "));
        countryList.add(new CountryGetSet("CX", "Christmas Island "));
        countryList.add(new CountryGetSet("IT", "Italy "));
        countryList.add(new CountryGetSet("PY", "Paraguay "));
        countryList.add(new CountryGetSet("US", "United States "));
        countryList.add(new CountryGetSet("CC", "Cocos (Keeling) Islands "));
        countryList.add(new CountryGetSet("JM", "Jamaica "));
        countryList.add(new CountryGetSet("PE", "Peru "));
        countryList.add(new CountryGetSet("UM", "United States Minor Outlying Islands "));
        countryList.add(new CountryGetSet("CO", "Colombia "));
        countryList.add(new CountryGetSet("JP", "Japan "));
        countryList.add(new CountryGetSet("PH", "Philippines "));
        countryList.add(new CountryGetSet("UY", "Uruguay "));
        countryList.add(new CountryGetSet("KM", "Comoros "));
        countryList.add(new CountryGetSet("JE", "Jersey "));
        countryList.add(new CountryGetSet("PN", "Pitcairn "));
        countryList.add(new CountryGetSet("UZ", "Uzbekistan "));
        countryList.add(new CountryGetSet("CG", "Congo "));
        countryList.add(new CountryGetSet("JO", "Jordan "));
        countryList.add(new CountryGetSet("PL", "Poland "));
        countryList.add(new CountryGetSet("VU", "Vanuatu "));
        countryList.add(new CountryGetSet("CD", "Congo, the Democratic Republic of the"));
        countryList.add(new CountryGetSet("KZ", "Kazakhstan "));
        countryList.add(new CountryGetSet("PT", "Portugal "));
        countryList.add(new CountryGetSet("VE", "Venezuela, Bolivarian Republic of "));
        countryList.add(new CountryGetSet("CK", "Cook Islands "));
        countryList.add(new CountryGetSet("KE", "Kenya "));
        countryList.add(new CountryGetSet("PR", "Puerto Rico "));
        countryList.add(new CountryGetSet("VN", "Viet Nam "));
        countryList.add(new CountryGetSet("CR", "Costa Rica "));
        countryList.add(new CountryGetSet("KI", "Kiribati "));
        countryList.add(new CountryGetSet("QA", "Qatar"));
        countryList.add(new CountryGetSet("VG", "Virgin Islands, British "));
        countryList.add(new CountryGetSet("CI", "Cote d'Ivoire !Côte d'Ivoire "));
        countryList.add(new CountryGetSet("KP", "Korea, Democratic People's Republic of"));
        countryList.add(new CountryGetSet("VI", "Reunion !Réunion RE Virgin Islands, U.S. "));
        countryList.add(new CountryGetSet("HR", "Croatia "));
        countryList.add(new CountryGetSet("KR", "Korea, Republic of "));
        countryList.add(new CountryGetSet("RO", "Romania "));
        countryList.add(new CountryGetSet("WF", "Wallis and Futuna "));
        countryList.add(new CountryGetSet("CU", "Cuba "));
        countryList.add(new CountryGetSet("KW", "Kuwait "));
        countryList.add(new CountryGetSet("RU", "Russian Federation "));
        countryList.add(new CountryGetSet("EH", "Western Sahara "));
        countryList.add(new CountryGetSet("CW", "Curacao !Curaçao "));
        countryList.add(new CountryGetSet("KG", "Kyrgyzstan "));
        countryList.add(new CountryGetSet("RW", "Rwanda "));
        countryList.add(new CountryGetSet("YE", "Yemen "));
        countryList.add(new CountryGetSet("CY", "Cyprus "));
        countryList.add(new CountryGetSet("LA", "Lao People's Democratic Republic "));
        countryList.add(new CountryGetSet("BL", "Saint Barthelemy !Saint Barthélemy "));
        countryList.add(new CountryGetSet("ZM", "Zambia "));
        countryList.add(new CountryGetSet("CZ", "Czech Republic "));
        countryList.add(new CountryGetSet("LV", "Latvia "));
        countryList.add(new CountryGetSet("SH", "Saint Helena, Ascension and Tristan da Cunha"));
        countryList.add(new CountryGetSet("ZW", "Zimbabwe "));
        countryList.add(new CountryGetSet("DK", "Denmark "));
        countryList.add(new CountryGetSet("LB", "Lebanon "));
        countryList.add(new CountryGetSet("KN", "Saint Kitts and Nevis "));
        countryList.add(new CountryGetSet("DJ", "Djibouti"));
        countryList.add(new CountryGetSet("LS", "Lesotho "));
        countryList.add(new CountryGetSet("LC", "Saint Lucia "));
        countryList.add(new CountryGetSet("DM", "Dominica "));
        countryList.add(new CountryGetSet("LR", "Liberia "));
        countryList.add(new CountryGetSet("MF", "Saint Martin (French part) "));
    }


}
